# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='id',
            new_name='article_id',
        ),
    ]
