# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 19:15
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20160326_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=localflavor.us.models.PhoneNumberField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ssn',
            field=localflavor.us.models.USSocialSecurityNumberField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(max_length=10, null=True),
        ),
    ]
